### ISSUE TITLE
Wrong "Invite Used" - Logger Takes Most Recent Invite and Applies it as the Invite Used

### ISSUE THREAD

**Issue by MarkLaBarr** [curtisf/logger#11]
Logger uses the most recent invite created as the "Invite Used" when creating the info card for a new member. Oftentimes, this is not correct.

**Comment by curtisf** [comment]
Logger's invite tracking logic was made before invite creation and deletion events were released. As of now, it will not update stored invites as they are created or deleted, and instead solely inside of guildMemberRemove. As you saw, this does introduce cases where the invite displayed isn't always correct. The plan is to fix this with the release for intents when I get to it.

**Comment by madollie** [comment]
PASTE_CREATE_ENDPOINT=host your own haste-server instance to get this
PGUSER=postgresusername
PGPASSWORD=postgrespassword
PGHOST=localhost
PGDATABASE=logger
REDIS_LOCK_TTL=2000
AES_KEY=youraeskey
MESSAGE_HISTORY_DAYS=how many days as an int you want to be wiped from db
BEZERK_URI=ws://localhost:1234
BEZERK_SECRET=https://github.com/thesharks/bezerk
RAVEN_URI=sentry uri from sentry.io
STAT_SUBMISSION_INTERVAL=

where do i find all that?

**Comment by curtisf** [comment]
The reworked invite system is out in production, which hopefully fixes this problem.
