### ISSUE TITLE
Bug fix and feature request: Fix the guildUpdate event

### ISSUE THREAD

**Issue by Derpitron** [curtisf/logger#23]
Bug: When I change the server icon of a server, the bot does not specify what exactly changed, it only says "unknown". this is detrimental as, in my server the icon changes frequently and I need to keep track of it.
![image](https://user-images.githubusercontent.com/46134462/123046470-c340b200-d419-11eb-8124-d25510397bf2.png)

Feature request: while the aforementioned behavior is obviously unintended, I think a good feature would be to show a larger embed with the newly changed server icon.

**Comment by curtisf** [comment]
many of these were fixed in the last update
